Fixed - Bug 2928 - License request generation broken on SSA
Signed-off-by: Bala.FA <bala@gluster.com>

diff --git a/gluster-lic-request.in b/gluster-lic-request.in
--- a/gluster-lic-request.in
+++ b/gluster-lic-request.in
@@ -89,8 +89,11 @@ EOF
 
         hostname=$(ssh $server hostname --fqdn);
         if [ $? -ne 0 ]; then
-            echo "failed to get hostname (skipping)";
-            continue
+            hostname=$(ssh $server hostname);
+            if [ $? -ne 0 ]; then
+		echo "failed to get hostname (skipping)";
+		continue
+	    fi
         fi
 
         echo "($macid $hostname)"
