Fixed - Bug 2327 - Provide --help support for all gluster-* scripts
Signed-off-by: Bala.JA <bala@gluster.com>

diff --git a/gluster-lic-info.in b/gluster-lic-info.in
--- a/gluster-lic-info.in
+++ b/gluster-lic-info.in
@@ -1,6 +1,9 @@
 #!/bin/bash
 
 
+ME=$(basename $0);
+
+
 function default_expiry()
 {
     aT=$(stat -c '%X' /.epoch);
@@ -77,8 +80,51 @@ EOF
 }
 
 
+function show_help()
+{
+    cat <<EOF
+Gluster Licensing Tools, Version @PACKAGE_VERSION@."
+
+Usage:  $ME [-h]
+
+Display Gluster license information.
+
+Miscellaneous:
+  -h                        display this help and exit
+
+Example:
+  $ME
+EOF
+}
+
+
 function main()
 {
+    # Parse command line arguments.
+    while getopts :h OPT; do
+	case "$OPT" in
+	    h)
+		show_help
+		exit 0
+		;;
+	    \?)
+                # getopts issues an error message
+		echo "Invalid option: -$OPTARG"
+		show_help
+		exit 1
+		;;
+	esac
+    done
+
+    # Remove the switches we parsed above.
+    shift `expr $OPTIND - 1`
+
+    # We want no non-option argument.
+    if [ $# -ne 0 ]; then
+	show_help
+	exit 1
+    fi
+
     macid=$(cat /.epoch 2>/dev/null);
 
     if [ -z "$macid" ]; then
diff --git a/gluster-lic-install.in b/gluster-lic-install.in
--- a/gluster-lic-install.in
+++ b/gluster-lic-install.in
@@ -1,6 +1,9 @@
 #!/bin/bash
 
 
+ME=$(basename $0);
+
+
 function validate_license()
 {
     echo -n "Validating signature ... "
@@ -18,8 +21,52 @@ function validate_license()
 }
 
 
+function show_help()
+{
+    cat <<EOF
+Gluster Licensing Tools, Version @PACKAGE_VERSION@."
+
+Usage:  $ME [-h] LICENSE-ASC-FILE
+
+Install Gluster license.  LICENSE-ASC-FILE is the license file
+generated by Gluster Inc.
+
+Miscellaneous:
+  -h                        display this help and exit
+
+Example:
+  $ME license.asc
+EOF
+}
+
+
 function main()
 {
+    # Parse command line arguments.
+    while getopts :h OPT; do
+	case "$OPT" in
+	    h)
+		show_help
+		exit 0
+		;;
+	    \?)
+                # getopts issues an error message
+		echo "Invalid option: -$OPTARG"
+		show_help
+		exit 1
+		;;
+	esac
+    done
+
+    # Remove the switches we parsed above.
+    shift `expr $OPTIND - 1`
+
+    # We want only one non-option argument.
+    if [ $# -ne 1 ]; then
+	show_help
+	exit 1
+    fi
+
     server_list=$(gluster peer status 2>/dev/null | grep -i hostname: | cut -f2 -d: );
 
     if [ -z "$server_list" ]; then
@@ -36,15 +83,6 @@ For more information refer the documentation available at
 
 EOF
         exit
-    fi
-
-    if [ $# -ne 1 ]; then
-        cat <<EOF
-
-Usage: $0 <LICENSE.ASC>
-
-EOF
-        exit 1
     fi
 
     validate_license $1;
diff --git a/gluster-lic-request.in b/gluster-lic-request.in
--- a/gluster-lic-request.in
+++ b/gluster-lic-request.in
@@ -1,8 +1,54 @@
 #!/bin/bash
 
 
+ME=$(basename $0);
+
+
+function show_help()
+{
+    cat <<EOF
+Gluster Licensing Tools, Version @PACKAGE_VERSION@."
+
+Usage:  $ME [-h]
+
+Generate license.req file.
+
+Miscellaneous:
+  -h                        display this help and exit
+
+Example:
+  $ME
+EOF
+}
+
+
 function main()
 {
+    # Parse command line arguments.
+    while getopts :h OPT; do
+	case "$OPT" in
+	    h)
+		show_help
+		exit 0
+		;;
+	    \?)
+                # getopts issues an error message
+		echo "Invalid option: -$OPTARG"
+		show_help
+		exit 1
+		;;
+	esac
+    done
+
+    # Remove the switches we parsed above.
+    shift `expr $OPTIND - 1`
+
+    # We want no non-option argument.
+    if [ $# -ne 0 ]; then
+	show_help
+	exit 1
+    fi
+
     server_list=$(gluster peer status 2>/dev/null | grep -i hostname: | cut -f2 -d: );
     now=$(date '+%s');
     environment="Virtual";
diff --git a/gluster-lic-sign.in b/gluster-lic-sign.in
--- a/gluster-lic-sign.in
+++ b/gluster-lic-sign.in
@@ -1,6 +1,9 @@
 #!/bin/bash -e
 
 
+ME=$(basename $0);
+
+
 function validate_uuid()
 {
     left=$(echo $1 | sed -r 's/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}//g');
@@ -122,24 +125,56 @@ EOF
 }
 
 
+function show_help()
+{
+    cat <<EOF
+Gluster Licensing Tools, Version @PACKAGE_VERSION@."
+
+Usage:  $ME [-h] LICENSE-REQ-FILE [NUM-DAYS]
+
+Sign license of Gluster servers.  LICENSE-REQ-FILE is a file created
+with gluster-lic-request tool on the Gluster cluster.  NUM-DAYS is
+number of days for which the generated license should be valid from
+the time of signing (ie from now).
+
+Miscellaneous:
+  -h                        display this help and exit
+
+Example:
+  $ME license.req
+  $ME license.req 365
+EOF
+}
+
+
 function main()
 {
-    now=$(date '+%s');
+    # Parse command line arguments.
+    while getopts :h OPT; do
+	case "$OPT" in
+	    h)
+		show_help
+		exit 0
+		;;
+	    \?)
+                # getopts issues an error message
+		echo "Invalid option: -$OPTARG"
+		show_help
+		exit 1
+		;;
+	esac
+    done
 
+    # Remove the switches we parsed above.
+    shift `expr $OPTIND - 1`
+
+    # We want only one or two non-option arguments.
     if [ $# -lt 1 -o $# -gt 2 ]; then
-        cat <<EOF
-
-Usage: $0 <LICENSE.REQ> [NUM-DAYS]
-
-<LICENSE.REQ> - License request file created with gluster-lic-request
-                on the Gluster cluster.
-
-[NUM-DAYS]    - Number of days for which the generated license should
-                be valid, from the time of signing (i.e from now.)
-EOF
-
-        exit
+	show_help
+	exit 1
     fi
+
+    now=$(date '+%s');
 
     validate_license_request "$1";
 
